### ISSUE TITLE
Pulse audio error

### ISSUE THREAD

**Issue by odelljw** [JeffHoogland/qAndora#20]
Jeff,  Any idea what mite cause this error?

pi@raspberrypi:~ $ qAndora
[025b5948] pulse audio output error: PulseAudio server connection failure: Connection refused
Traceback (most recent call last):
  File "qAndora.py", line 597, in <module>
    mainWin = MainWindow()
  File "qAndora.py", line 46, in __init__
    self.assignWidgets()
  File "qAndora.py", line 251, in assignWidgets
    self.muteButton.clicked.connect(self.mutePressed)
AttributeError: 'MainWindow' object has no attribute 'muteButton'
Thaks for your help regards,

**Comment by JeffHoogland** [comment]
Do your other applications play audio as expected? That error implies pulse audio isn't working on your system I believe.
